spring:
    application:
      name: banking-system

    datasource:
      url: jdbc:postgresql://localhost:5432/banking_system_db
      username: postgres
      password: password

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          globally_quoted_identifiers: true
          jdbc:
            time_zone: UTC

    cache:
      type: redis

    data:
      redis:
        host: localhost
        port: 6379

    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: http://localhost:8080/oauth2/jwks

value :
  bin:   "123"
  redirect-uri: "http://localhost:8081/oauth2/callback"
  client-id: "banking-system-client"
  client-secret: "a-secret"
  scope-read: "read"
  scope-write: "write"
  authorization-uri: "oauth2/authorize"
  token-uri: "oauth2/token"
  token-introspection-uri: "oauth2/introspect"
  token-revocation-uri: "oauth2/revoke"
  oicd-user-info-uri: "user-info"
  jwk-set-uri: "oauth2/jwks"
  logout-uri: "oauth2/logout"
  origin-uri: "http://localhost:5173"
  post-basic-secret: "YmFua2luZy1zeXN0ZW0tY2xpZW50OmEtc2VjcmV0"