package com.example.banking_system.domain.account.validator;

import com.example.banking_system.common.exception.ValidationException;
import com.example.banking_system.domain.account.dto.UpdateAccountRequest;
import com.example.banking_system.domain.account.entity.Account;
import com.example.banking_system.domain.account.service.domain.AccountService;
import com.example.banking_system.domain.account.service.query.AccountQueryService;
import com.example.banking_system.common.utility.Util;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.time.temporal.ChronoUnit;

@Component
@RequiredArgsConstructor
public class AccountValidator {
    private final AccountQueryService accountQueryService;
    private final AccountService accountService;
    private final Util util;


    public void validateCreate(Account account) {
        util.assertUnique(accountQueryService.existsByUsername(account.getUsername()),"Username already exists");
        util.assertUnique(accountQueryService.existsByPhoneNumber(account.getPhoneNumber()),"Phone number already exists");
        util.assertUnique(accountQueryService.existsByEmail(account.getEmail()),"Email already exists");

    }
    //not check account number uniqueness because it is generated by system and guaranteed to be unique
    public void validateUpdate(UpdateAccountRequest request,Account existingAccount) {

        boolean updatedAccountIn48Hours = existingAccount.getUpdatedAt() != null
                && existingAccount.getUpdatedAt().plus(48, ChronoUnit.HOURS).isAfter(Instant.now());

        if (updatedAccountIn48Hours) {throw new ValidationException("account can only be updated once every 48 hours");}
        setNonNullFieldsToUpdateAccount(request,  existingAccount);
    }

    // set only non-null fields from request to existingAccount after validating uniqueness
    public void setNonNullFieldsToUpdateAccount(UpdateAccountRequest request, Account existingAccount){
        if (request.getEmail() != null && !request.getEmail().equals(existingAccount.getEmail())) {
            util.assertUnique(accountQueryService.existsByEmail(request.getEmail()), "Email already exists");
            existingAccount.setEmail(request.getEmail());
        }

        if (request.getPhoneNumber() != null && !request.getPhoneNumber().equals(existingAccount.getPhoneNumber())) {
            util.assertUnique(accountQueryService.existsByPhoneNumber(request.getPhoneNumber()), "Phone number already exists");
            existingAccount.setPhoneNumber(request.getPhoneNumber());
        }

        if(request.getAddress() != null  && !request.getAddress().equals(existingAccount.getAddress())) {
            existingAccount.setAddress(request.getAddress());
        }


    }

}
